### ISSUE TITLE
shifters broken in update 1.1.3

### ISSUE THREAD

**Issue by gaminggirl** [North-West-Wind/SkyFarmCore#12]
All the shifters broke in update 1.1.3 nether shifter over the edge you just fall in circles no matter if shifter is in shifter or boot slot. End shifter does nothing when pressing shift in neither of those slots. Twilight forest and undergarten shifters same thing. Crafting a new one makes no difference either.

**Comment by North-West-Wind** [comment]
Just released 1.1.4. That fixed the issue
