### ISSUE TITLE
version 1.1.6 crash when searching recipes in JEI

### ISSUE THREAD

**Issue by ShyMaiden** [North-West-Wind/SkyFarmCore#14]
After updating the pack, I experienced several crashes when typing things in the JEI search bar. I could search many things without problems. I haven't experienced the problem in older versions, but also probably didn't do the problematic searches.
It did crash when typing 'reds', just 'red' was fine. Also crashed on 'blue d', I have not yet tried just 'blue', because honestly I got tired of restarting the pack today (reloading the world after the crash didn't work every time).
I included the logs of the crashes for more information.

[crash-2021-07-23_13.39.02-client.txt](https://github.com/North-West-Wind/SkyFarmCore/files/6870085/crash-2021-07-23_13.39.02-client.txt)
[crash-2021-07-23_13.41.05-client.txt](https://github.com/North-West-Wind/SkyFarmCore/files/6870087/crash-2021-07-23_13.41.05-client.txt)
[crash-2021-07-23_18.01.44-client.txt](https://github.com/North-West-Wind/SkyFarmCore/files/6870088/crash-2021-07-23_18.01.44-client.txt)
[crash-2021-07-23_12.43.49-client.txt](https://github.com/North-West-Wind/SkyFarmCore/files/6870089/crash-2021-07-23_12.43.49-client.txt)

**Comment by North-West-Wind** [comment]
This is caused by Sodium Reforged. You can fix it by updating Sodium Reforged yourself.
Modpack update will come later to fix this.

**Comment by ShyMaiden** [comment]
thanks for the tip, I'll try that.

**Comment by North-West-Wind** [comment]
Modpack updated :)
