### ISSUE TITLE
create mixer not crafting dye seed

### ISSUE THREAD

**Issue by ShyMaiden** [North-West-Wind/SkyFarmCore#15]
I'll start by admitting I'm still new to create, so please forgive me if I'm overlooking something.

I don't seem to be able to craft the due seed in the mixer, because of recipe conflicts with other dyes. So far I have gotten light blue dye and orange dye instead of the seeds I wanted to get. After some reading up on create, I found that you can use a filter on the basin to prevent recipe conflicts, but for that you need the item you want to make.

Am I overlooking something?

**Comment by North-West-Wind** [comment]
Alright. This is a Create problem that I can't fix, but that doesn't mean you can't have a workaround.

Here are 2 things you can try:
1. Throw in the water seeds first, then the dyes
2. Put a random item in the filter. When you're done putting everything in the basin, remove the item from the filter.

**Comment by ShyMaiden** [comment]
I've tried both, but it still mixes orange or light blue dye, not the dye seeds, unfortunately.

**Comment by North-West-Wind** [comment]
Try disconnecting the mixer from the rotations, put in everything and reconnect them.
