### ISSUE TITLE
Applied Energistics 2 ME Storage System - missing items in search

### ISSUE THREAD

**Issue by SniketTheLlama** [North-West-Wind/SkyFarmCore#17]
I made the AE2 storage system and tried searching for some items I put in there via the crafting terminal. Notably Iron Ingots and any seeds. These are missing only when typing in the search. If I manually look for the item via crafting terminal, I can find them. They are there.

**Comment by North-West-Wind** [comment]
Might be an AE2 problem. You may want to report to them instead.
[AE2 Issues](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues)
