### ISSUE TITLE
Press "D" in JEI and the game crashes

### ISSUE THREAD

**Issue by TimTacToe** [North-West-Wind/SkyFarmCore#18]
In the current version, if you start typing a d in JEI the games crashes then your world is stuck, the moment you open your inventory again the game crashes again. 

-- Ingredient being rendered --
Details:
	Mod Name: Quark
	Registry Name: quark:dirty_glass_pane
	Display Name: Dirty Glass Pane
	String Name: 1 dirty_glass_pane

**Comment by North-West-Wind** [comment]
I bet this is caused by Sodium Reforged.
You might want to report this to Quark though.

**Comment by TimTacToe** [comment]
Ok thank you.
