### ISSUE TITLE
Saltpeter seed seems to be uncraftable.

### ISSUE THREAD

**Issue by PKFire18** [North-West-Wind/SkyFarmCore#19]
One of the advancements requires crafting a saltpeter seed from Mystical Agriculture, but the recipe for the seed is either missing or not showing up in JEI.

**Comment by wizardofdocs** [comment]
Cyanite and Thermal Series rubber are other craftable materials that count toward the Mystical Agriculture seed advancement but have no seed recipe in JEI.

Additional seeds needed for this advancement (such as yellorium, platinum, and mithril) have uncraftable components.

**Comment by North-West-Wind** [comment]
Fixed in 1.2.2
By "fixed" I just removed the requirements from the advancement, not actually adding their recipes.
