### ISSUE TITLE
PneumaticCraft explosion conversion not working

### ISSUE THREAD

**Issue by wizardofdocs** [North-West-Wind/SkyFarmCore#20]
Steps to reproduce:
1. Create a blastproof environment (I used an obsidian box)
2. Place a TNT block in the blastproof area
3. Throw a stack of iron ingots on the floor block next to the TNT
4. Light the TNT and get out of the way

Expected behavior:
Some of the iron is destroyed, and the rest is converted into Compressed Iron

Actual behavior:
All the iron is destroyed and no Compressed Iron is created

**Comment by North-West-Wind** [comment]
Try using the Tiny TNT for now.

It seems some other mod is messing up the recipe. I will leave this open.

**Comment by North-West-Wind** [comment]
Apparently this is caused by Sodium (again).
This can't be fixed (by me).

**Comment by wizardofdocs** [comment]
Is there a survival workaround?
