### ISSUE TITLE
Uncraftable Animal Crops seeds

### ISSUE THREAD

**Issue by wizardofdocs** [North-West-Wind/SkyFarmCore#21]
There are no recipes for the vindicator or illusioner seeds, and they're needed to complete the Farming Mattocks advancement.

**Comment by North-West-Wind** [comment]
Those were 2 seeds I removed, but apparently I forgot to remove them from the advancement.
Will be fixed on the next update.

**Comment by North-West-Wind** [comment]
Fixed in 1.2.0
