### ISSUE TITLE
Missing recipes for some industrial foregoing items

### ISSUE THREAD

**Issue by waechtet** [North-West-Wind/SkyFarmCore#23]
SkyFarm 1.1.10b
There are no recipes for:
- All addons
- Pink Slime ingot
- Simple machine frame, advanced machine frame, supreme machine frame
- Mycelial reactor
- Mechanical dirt
- All infinity tools/backpacks

**Comment by North-West-Wind** [comment]
This is a problem on the Industrial Foregoing end.
While it is fixed on their latest update, Sky Farm still has the old version.
Will be fixed on the next update.

**Comment by North-West-Wind** [comment]
Fixed in 1.2.0
