### ISSUE TITLE
Chisel and Bits blocks not displaying properly

### ISSUE THREAD

**Issue by wizardofdocs** [North-West-Wind/SkyFarmCore#24]
This is an Iron Bricks block with one bit removed.
![image](https://user-images.githubusercontent.com/83661258/132115367-df546466-e4d2-4c56-affe-5b30c123218f.png)

This is a vanilla Block of Iron with some bits removed (left), and those bits laid out on the ground in a plane (right).
![image](https://user-images.githubusercontent.com/83661258/132115391-c34e6f14-64f4-40b8-8a9e-d8430e6be5ab.png)

**Comment by North-West-Wind** [comment]
This is caused by [Halogen](https://www.curseforge.com/minecraft/mc-mods/halogen) (a.k.a. Sodium). Future versions will have Chisels and Bits removed.
