### ISSUE TITLE
Cannot travel to any other dimension besides the end even wearing the correct boots

### ISSUE THREAD

**Issue by Citrus34** [North-West-Wind/SkyFarmCore#25]
Since I have crafted the Overworld Shifter  - End, I am no longer able to use the nether or twilight boots even when worn. falling into the void teleports me to the top of the world, and charging while wearing the twilight boots causes me to jump like the end boots.

**Comment by North-West-Wind** [comment]
Shifters should be put in Curios slot. They only work as boots when Curios is not present.
