### ISSUE TITLE
Vehicle mod not having craftable vehicles

### ISSUE THREAD

**Issue by TheNoobyTalker** [North-West-Wind/SkyFarmCore#27]
I've got a issue with the vehicle mod, its not letting me craft any vehicles after unlocking the "skill" for it.
Tried to ask in the Crayfish Discord but they weren't of great help.
Is there anything i could be missing?

**Comment by North-West-Wind** [comment]
What does it mean by not craftable?

**Comment by TheNoobyTalker** [comment]
They seem to not even be obtainable through commands or the creative jei menu, haven't tried the normal creative inventory yet.

**Comment by TheNoobyTalker** [comment]
The issue resolved itself, somehow..
Seems that my panels were ghost items.
Btw, Twilight forest freaks out when you remove and add the vehicle mod pack into the pack.
