### ISSUE TITLE
Random crashes on the SkyFarm-RELEASE-1.3.0

### ISSUE THREAD

**Issue by Shadowhisper** [North-West-Wind/SkyFarmCore#32]
[crash.txt](https://github.com/North-West-Wind/SkyFarmCore/files/7440245/crash.txt)

Old files were missing items in the world. Created new game everything was ok until i placed a Cauldron (iron) on a campfire. Idk what new changes were in this release but it's causing random crashes. No mods cause the crash base on the crash report. I will still keep trying to play.

**Comment by North-West-Wind** [comment]
This is caused by Magnesium. You can fix it temporarily by removing it.
