### ISSUE TITLE
bug chunk

### ISSUE THREAD

**Issue by onurbzinid** [North-West-Wind/SkyFarmCore#33]
after the new mod update (1.3.0) my chunk bronke, in this chunk is the portal to Twilight Forest

![2021-10-29_12 32 48](https://user-images.githubusercontent.com/47401218/139453793-96809021-8067-4776-92de-2db06120ab34.png)

[crash-2021-10-29_12.28.50-client.txt](https://github.com/North-West-Wind/SkyFarmCore/files/7442717/crash-2021-10-29_12.28.50-client.txt)

**Comment by North-West-Wind** [comment]
This is caused by Magnesium. You can fix it temporarily by removing it. Future updates will not include that.
