### ISSUE TITLE
Crash When Entering Nether

### ISSUE THREAD

**Issue by tloskpd** [North-West-Wind/SkyFarmCore#34]
ModPack Version SkyFarm - RELEASE 1.3.0

After making the nether boots to go to the nether, and jumping off my platform took me to the nether, I fell down and as I bounced (slimeboots) the game crashed with the following crash report

https://pastebin.com/8xT7rCH8

I also tested this in a creative world.  The superflat world didn't work at all (kept falling out of the world so I suspect that it cause it wasn't the skyfarm generated world).  I also tested in a sky farm world, jumped off, and landed to a Server Closed message, taking me to the multiplayer screen (even though I created a SP world).  Going back to the SP load screen, that test world didn't show up at all until I closed and relaunched the pack.  Loading into the world took me back to the "start" of the pack before I gave myself the boots.  Jumping off again, created the same problem.

I have already disabled magnesium due to chunk crashes.

**Comment by North-West-Wind** [comment]
Fixed in 1.3.1
